{
 "title": "Pinot",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "Controller Leader",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (pinot_controller_LeaderPartitionCount_Value)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Table Query QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (rate(pinot_broker_queries_Count[10m]))",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Table Query Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (table) (pinot_broker_queryExecution_50thPercentile) ",
     "legendFormat": "{{table}}-p50"
    },
    {
     "expr": "avg by (table) (pinot_broker_queryExecution_75thPercentile)",
     "legendFormat": "{{table}}-p75"
    },
    {
     "expr": "avg by (table) (pinot_broker_queryExecution_95thPercentile)",
     "legendFormat": "{{table}}-p95"
    },
    {
     "expr": "avg by (table) (pinot_broker_queryExecution_99thPercentile)",
     "legendFormat": "{{table}}-p99"
    },
    {
     "expr": "avg by (table) (pinot_broker_queryExecution_999thPercentile)",
     "legendFormat": "{{table}}-p999"
    }
   ]
  },
  {
   "title": "Pinot Server Documents Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (statefulset_kubernetes_io_pod_name) (pinot_server_documentCount_Value)",
     "legendFormat": "{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "Table Consuming Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (table) (pinot_server_freshnessLagMs_50thPercentile)",
     "legendFormat": "{{table}}-p50"
    },
    {
     "expr": "avg by (table) (pinot_server_freshnessLagMs_75thPercentile)",
     "legendFormat": "{{table}}-p75"
    },
    {
     "expr": "avg by (table) (pinot_server_freshnessLagMs_95thPercentile)",
     "legendFormat": "{{table}}-p95"
    },
    {
     "expr": "avg by (table) (pinot_server_freshnessLagMs_99thPercentile)",
     "legendFormat": "{{table}}-p99"
    },
    {
     "expr": "avg by (table) (pinot_server_freshnessLagMs_999thPercentile)",
     "legendFormat": "{{table}}-p999"
    }
   ]
  },
  {
   "title": "Table Ingestion Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic)  (avg by (partition) (rate(pinot_server_realtimeRowsConsumed_Count[5m])))",
     "legendFormat": "Received"
    },
    {
     "expr": "rate(kafka_events_published_total[5m])",
     "legendFormat": "Published"
    }
   ]
  },
  {
   "title": "Server Total Documents Per Table",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (pinot_server_documentCount_Value)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Server Query Processing Per Table",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (table) (pinot_server_queryProcessing_50thPercentile)",
     "legendFormat": "{{table}}-p50"
    },
    {
     "expr": "avg by (table) (pinot_server_queryProcessing_75thPercentile)",
     "legendFormat": "{{table}}-p75"
    },
    {
     "expr": "avg by (table) (pinot_server_queryProcessing_95thPercentile)",
     "legendFormat": "{{table}}-p95"
    },
    {
     "expr": "avg by (table) (pinot_server_queryProcessing_99thPercentile)",
     "legendFormat": "{{table}}-p99"
    },
    {
     "expr": "avg by (table) (pinot_server_queryProcessing_999thPercentile)",
     "legendFormat": "{{table}}-p999"
    }
   ]
  },
  {
   "title": "Server Total Query Time Per Table",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (table) (pinot_server_totalQueryTime_50thPercentile)",
     "legendFormat": "{{table}}-p50"
    },
    {
     "expr": "avg by (table) (pinot_server_totalQueryTime_75thPercentile)",
     "legendFormat": "{{table}}-p75"
    },
    {
     "expr": "avg by (table) (pinot_server_totalQueryTime_95thPercentile)",
     "legendFormat": "{{table}}-p95"
    },
    {
     "expr": "avg by (table) (pinot_server_totalQueryTime_99thPercentile)",
     "legendFormat": "{{table}}-p99"
    },
    {
     "expr": "avg by (table) (pinot_server_totalQueryTime_999thPercentile)",
     "legendFormat": "{{table}}-p999"
    }
   ]
  },
  {
   "title": "Pinot Server Off-Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (statefulset_kubernetes_io_pod_name)(pinot_server_realtime_offheapMemoryUsed_Value) ",
     "legendFormat": "{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "Realtime Table Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_namespace) (pinot_controller_realtimeTableCount_Value)",
     "legendFormat": "total table count"
    }
   ]
  },
  {
   "title": "Server Segment Build",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (statefulset_kubernetes_io_pod_name) (pinot_server_llcSimultaneousSegmentBuilds_Value)",
     "legendFormat": "{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "Server Query Doc Scanned Per Table",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (rate(pinot_server_numDocsScanned_Count[10m]))",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Pinot Server Memory Mapped Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (statefulset_kubernetes_io_pod_name)(pinot_server_memory_mmapBufferUsage_Value) ",
     "legendFormat": "{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "Server Query Segment Processed Per Table",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (rate(pinot_server_numSegmentsProcessed_Count[5m]))",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Server Query Doc Scanned",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (statefulset_kubernetes_io_pod_name) (rate(pinot_server_numDocsScanned_Count[10m]))",
     "legendFormat": "{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "Server DirectBuffer Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name)(pinot_server_memory_directBufferUsage_Value) ",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Server Query Segment Processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (statefulset_kubernetes_io_pod_name) (rate(pinot_server_numSegmentsProcessed_Count[5m]))",
     "legendFormat": "{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  }
 ]
}