apiVersion: 1

deleteDatasources:
- name: prometheus
  orgId: 1

datasources:
- name: prometheus
  type: prometheus
  typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
  access: proxy
  url: http://prometheus:9090
  password: ""
  user: ""
  database: ""
  basicAuth: false
  isDefault: true
  jsonData: {}
  readOnly: false