# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: [localhost:9090]

- job_name: pinot-controller
  static_configs:
  - targets: [pinot-controller:8888]
- job_name: pinot-broker
  static_configs:
  - targets: [pinot-broker:8888]
- job_name: pinot-server
  static_configs:
  - targets: [pinot-server:8888]